# Generated by Django 4.2.6 on 2023-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('synopsis', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('url', models.URLField()),
                ('image', models.URLField(null=True)),
                ('source', models.CharField(max_length=32)),
            ],
        ),
    ]
