# Generated by Django 4.2.6 on 2023-12-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookBrowseID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='bookBrowseID',
            field=models.IntegerField(null=True),
        ),
    ]
