# Generated by Django 4.2.6 on 2024-01-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0002_book_bookbrowseid_reviewer_bookbrowseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='data_load.book')),
                ('similarities', models.ManyToManyField(to='data_load.book')),
            ],
        ),
    ]
