# Generated by Django 4.2.6 on 2023-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0003_alter_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
    ]
