# Generated by Django 4.2.6 on 2024-01-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0004_alter_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alike',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='data_load.book'),
        ),
    ]
