# Generated by Django 4.2.6 on 2023-12-01 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0004_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
