# Generated by Django 4.2.6 on 2023-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0005_book_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(null=True),
        ),
    ]
